# to compile tcpserver and tcpclient
tcp:
	gcc -w -o server tcp_server.c
	gcc -w -o client tcp_client.c

# to compile udpserver and udpclient
udp:
	gcc -w -o userver udp_server.c
	gcc -w -o uclient udp_client.c